text_input = input("Enter some text: ")
text_input= text_input.replace("a","4")
text_input= text_input.replace("b","8")
text_input= text_input.replace("e","3")
text_input= text_input.replace("l","1")
text_input= text_input.replace("o","0")
text_input= text_input.replace("s","5")
text_input= text_input.replace("t","7")
print(text_input)

